// NOTE: This file is auto-generated by vite-envs.
// It enables you to access environment variables in your service worker.
// To use it, use `importScripts("swEnv.js")` at the top of your worker file.
// (Assuming your worker file is next to this file)
// Then you can access your environment variables via `self.__VITE_ENVS.MY_VAR`

const envWithValuesInBase64 = {
  "BASE_URL": "Ii90ZXN0LXZpdGUtZW52cy1keW5hbWljLWJhc2UvIg==",
  "MODE": "InByb2R1Y3Rpb24i",
  "DEV": "ZmFsc2U=",
  "PROD": "dHJ1ZQ==",
  "BUILD_TIME": "MTcyNDExNDI3MTUyOQ==",
  "VERSION": "IjQuMi4yIg==",
  "TITLE": "IkRlZmF1bHQgVGl0bGUg8J+agCI=",
  "DESCRIPTION": "IiI="
};
const env = {};
Object.keys(envWithValuesInBase64).forEach(function (name) {
    env[name] = JSON.parse(
      new TextDecoder().decode(
        Uint8Array.from(
          atob(envWithValuesInBase64[name]),
          c => c.charCodeAt(0)
        )
      )
    );
});
self.__VITE_ENVS = env;